export const data = [
  { id: "alligator", name: { "en-us": "Alligator", "pt-br": "Jacaré" } },
  { id: "alpaca", name: { "en-us": "Alpaca", "pt-br": "Alpaca" } },
  { id: "anteater", name: { "en-us": "Anteater", "pt-br": "Tamanduá" } },
  { id: "antelope", name: { "en-us": "Antelope", "pt-br": "Antílope" } },
  { id: "ape", name: { "en-us": "Ape", "pt-br": "Símio" } },
  { id: "bat", name: { "en-us": "Bat", "pt-br": "Morcego" } },
  { id: "bee", name: { "en-us": "Bee", "pt-br": "Abelha" } },
  {
    id: "bowhead-whale",
    name: { "en-us": "Bowhead Whale", "pt-br": "Baleia Franca" },
  },
  { id: "buffalo", name: { "en-us": "Buffalo", "pt-br": "Búfalo" } },
  { id: "butterfly", name: { "en-us": "Butterfly", "pt-br": "Borboleta" } },
  { id: "camel", name: { "en-us": "Camel", "pt-br": "Camelo" } },
  { id: "cat", name: { "en-us": "Cat", "pt-br": "Gato" } },
  { id: "chicken", name: { "en-us": "Chicken", "pt-br": "Frango" } },
  { id: "cow", name: { "en-us": "Cow", "pt-br": "Vaca" } },
  { id: "crow", name: { "en-us": "Crow", "pt-br": "Corvo" } },
  { id: "dinosaur", name: { "en-us": "Dinosaur", "pt-br": "Dinossauro" } },
  { id: "dog", name: { "en-us": "Dog", "pt-br": "Cão" } },
  { id: "dove", name: { "en-us": "Dove", "pt-br": "Pombo" } },
  { id: "duck", name: { "en-us": "Duck", "pt-br": "Pato" } },
  { id: "elephant", name: { "en-us": "Elephant", "pt-br": "Elefante" } },
  { id: "falcon", name: { "en-us": "Falcon", "pt-br": "Falcão" } },
  { id: "ferret", name: { "en-us": "Ferret", "pt-br": "Furão" } },
  { id: "frog", name: { "en-us": "Frog", "pt-br": "Sapo" } },
  { id: "giraffe", name: { "en-us": "Giraffe", "pt-br": "Girafa" } },
  {
    id: "guinea-pig",
    name: { "en-us": "Guinea Pig", "pt-br": "Porquinho-da-índia" },
  },
  { id: "hedgehog", name: { "en-us": "Hedgehog", "pt-br": "Ouriço" } },
  {
    id: "hippopotamus",
    name: { "en-us": "Hippopotamus", "pt-br": "Hipopótamo" },
  },
  { id: "horse", name: { "en-us": "Horse", "pt-br": "Cavalo" } },
  {
    id: "humpback-whale",
    name: { "en-us": "Humpback Whale", "pt-br": "Baleia Jubarte" },
  },
  { id: "hyena", name: { "en-us": "Hyena", "pt-br": "Hiena" } },
  {
    id: "komodo-dragon",
    name: { "en-us": "Komodo Dragon", "pt-br": "Dragão de Komodo" },
  },
  { id: "leopard", name: { "en-us": "Leopard", "pt-br": "Leopardo" } },
  { id: "lion", name: { "en-us": "Lion", "pt-br": "Leão" } },
  { id: "lizard", name: { "en-us": "Lizard", "pt-br": "Lagarto" } },
  { id: "moose", name: { "en-us": "Moose", "pt-br": "Alce" } },
  { id: "otter", name: { "en-us": "Otter", "pt-br": "Lontra" } },
  { id: "owl", name: { "en-us": "Owl", "pt-br": "Coruja" } },
  { id: "panda", name: { "en-us": "Panda", "pt-br": "Panda" } },
  { id: "penguin", name: { "en-us": "Penguin", "pt-br": "Pinguim" } },
  { id: "pig", name: { "en-us": "Pig", "pt-br": "Porco" } },
  { id: "rabbit", name: { "en-us": "Rabbit", "pt-br": "Coelho" } },
  { id: "raccoon", name: { "en-us": "Raccoon", "pt-br": "Guaxinim" } },
  { id: "rat", name: { "en-us": "Rat", "pt-br": "Rato" } },
  { id: "rattlesnake", name: { "en-us": "Rattlesnake", "pt-br": "Cascavel" } },
  { id: "rhinoceros", name: { "en-us": "Rhinoceros", "pt-br": "Rinoceronte" } },
  { id: "robin", name: { "en-us": "Robin", "pt-br": "Pisco" } },
  { id: "rooster", name: { "en-us": "Rooster", "pt-br": "Galo" } },
  { id: "scorpion", name: { "en-us": "Scorpion", "pt-br": "Escorpião" } },
  { id: "shark", name: { "en-us": "Shark", "pt-br": "Tubarão" } },
  { id: "sheep", name: { "en-us": "Sheep", "pt-br": "Ovelha" } },
  { id: "swan", name: { "en-us": "Swan", "pt-br": "Cisne" } },
  { id: "tiger", name: { "en-us": "Tiger", "pt-br": "Tigre" } },
  { id: "turkey", name: { "en-us": "Turkey", "pt-br": "Peru" } },
  { id: "wolf", name: { "en-us": "Wolf", "pt-br": "Lobo" } },
  { id: "yak", name: { "en-us": "Yak", "pt-br": "Iaque" } },
  { id: "zebra", name: { "en-us": "Zebra", "pt-br": "Zebra" } },
];
